"""Local trainable Cognix synthesis policy.

This module implements a small, auditable model artifact for source-grounded
answer synthesis. It is not a foundation model. It learns answer structure and
term salience from Cognix SFT JSONL, then generates extractive answers from the
retrieved evidence supplied at runtime.
"""

from __future__ import annotations

import hashlib
import json
import math
import re
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app.services.retrieval_types import RetrievedChunk

MODEL_TYPE = "cognix_micro_synthesis_v1"
TOKEN_PATTERN = re.compile(r"[a-zA-Z0-9_][a-zA-Z0-9_\-]*")
HEADING_PATTERN = re.compile(r"^(#{1,3})\s+(.+?)\s*$", re.MULTILINE)
STOPWORDS = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "by",
    "for",
    "from",
    "has",
    "have",
    "in",
    "is",
    "it",
    "of",
    "on",
    "or",
    "that",
    "the",
    "this",
    "to",
    "was",
    "were",
    "what",
    "when",
    "where",
    "which",
    "who",
    "why",
    "with",
}


@dataclass(frozen=True)
class SynthesisExample:
    """One SFT example reduced to the fields this model can learn from."""

    question: str
    assistant: str


class CognixMicroModel:
    """A trained local answer-structure and evidence-selection policy."""

    def __init__(self, payload: dict[str, Any]) -> None:
        if payload.get("model_type") != MODEL_TYPE:
            raise ValueError(f"Unsupported Cognix micro-model type: {payload.get('model_type')}")
        self.payload = payload
        self.title_heading = str(payload.get("title_heading") or "Research Memo")
        self.answer_heading = str(payload.get("answer_heading") or "Answer")
        self.evidence_heading = str(payload.get("evidence_heading") or "Evidence")
        self.include_question = bool(payload.get("include_question", True))
        self.bullet_answer = bool(payload.get("bullet_answer", True))
        self.sentence_limit = int(payload.get("sentence_limit", 5))
        self.term_weights = {str(key): float(value) for key, value in dict(payload.get("term_weights") or {}).items()}

    def synthesize(self, question: str, chunks: list[RetrievedChunk], style: str = "memo") -> str:
        """Generate a source-grounded answer from retrieved chunks."""
        title = "Answer" if style == "brief" else self.title_heading
        if not chunks:
            return (
                f"# {title}\n\n"
                f"I could not find enough indexed evidence to answer: {question}\n\n"
                "Add relevant files to `data/raw/`, run ingest, then ask again.\n"
            )

        sentence_limit = 2 if style == "brief" else self.sentence_limit
        selected = select_evidence_sentences(question, chunks, self.term_weights, sentence_limit)
        lines = [f"# {title}", ""]
        if self.include_question:
            lines.extend([f"**Question:** {question}", ""])
        lines.extend([f"## {self.answer_heading}"])
        if selected:
            for sentence, chunk in selected:
                citation = f"`source: {chunk.source_path}, chunk: {chunk.chunk_id}`"
                prefix = "- " if self.bullet_answer else ""
                lines.append(f"{prefix}{sentence} {citation}")
        else:
            top = chunks[0]
            lines.append(
                "The retrieved evidence is related, but it does not contain a clean direct statement "
                f"answering the question. Strongest source: `{top.source_path}`, chunk {top.chunk_id}."
            )
        if style != "brief":
            lines.extend(["", f"## {self.evidence_heading}"])
            for index, chunk in enumerate(chunks, start=1):
                lines.append(f"{index}. {chunk.excerpt} `source: {chunk.source_path}, chunk: {chunk.chunk_id}`")
            lines.extend(
                [
                    "",
                    "## Retrieval Notes",
                    f"- Retrieved {len(chunks)} chunks.",
                    "- Answer generated by local trained Cognix micro-synthesis policy.",
                ]
            )
        return "\n".join(lines).strip() + "\n"

    def save(self, path: Path) -> Path:
        """Persist the model payload to JSON."""
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(self.payload, indent=2, sort_keys=True), encoding="utf-8")
        return path


def train_cognix_micro_model(dataset_path: Path, output_path: Path) -> tuple[CognixMicroModel, dict[str, Any]]:
    """Train and save a Cognix micro-synthesis artifact from SFT JSONL."""
    examples = load_sft_examples(dataset_path)
    if not examples:
        raise ValueError("SFT dataset contains no trainable Cognix examples.")
    raw_bytes = dataset_path.read_bytes()
    assistant_text = "\n\n".join(example.assistant for example in examples)
    title_heading = most_common_heading(examples, level="#") or "Research Memo"
    answer_heading = most_common_named_heading(examples, {"answer", "short answer", "analysis", "summary"}) or "Answer"
    evidence_heading = most_common_named_heading(examples, {"evidence", "sources", "citations"}) or "Evidence"
    bullet_answer = bullet_line_ratio(assistant_text) >= 0.25
    sentence_limit = max(2, min(8, round(mean_answer_sentences(examples))))
    term_weights = learned_term_weights(examples)
    payload = {
        "model_type": MODEL_TYPE,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "dataset_path": str(dataset_path),
        "dataset_sha256": hashlib.sha256(raw_bytes).hexdigest(),
        "examples": len(examples),
        "title_heading": title_heading,
        "answer_heading": answer_heading,
        "evidence_heading": evidence_heading,
        "include_question": "**question:**" in assistant_text.lower(),
        "bullet_answer": bullet_answer,
        "sentence_limit": sentence_limit,
        "term_weights": term_weights,
    }
    model = CognixMicroModel(payload)
    model.save(output_path)
    metrics = {
        "examples": len(examples),
        "dataset_sha256": payload["dataset_sha256"],
        "term_count": len(term_weights),
        "sentence_limit": sentence_limit,
        "bullet_answer": bullet_answer,
    }
    return model, metrics


def load_cognix_micro_model(path: Path) -> CognixMicroModel:
    """Load a trained Cognix micro-synthesis artifact."""
    return CognixMicroModel(json.loads(path.read_text(encoding="utf-8")))


def load_sft_examples(path: Path) -> list[SynthesisExample]:
    """Load chat-style SFT examples exported by Cognix."""
    examples: list[SynthesisExample] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            record = json.loads(line)
            messages = record.get("messages")
            if not isinstance(messages, list):
                raise ValueError(f"Line {line_number} has no messages array.")
            user = first_message(messages, "user")
            assistant = first_message(messages, "assistant")
            if user and assistant:
                examples.append(SynthesisExample(question=extract_question(user), assistant=assistant.strip()))
    return examples


def first_message(messages: list[Any], role: str) -> str:
    """Return the first message content for a role."""
    for message in messages:
        if isinstance(message, dict) and message.get("role") == role and message.get("content"):
            return str(message["content"])
    return ""


def extract_question(user_content: str) -> str:
    """Extract the question part from a Cognix SFT user message."""
    match = re.search(r"Question:\s*(.+?)(?:\n\n|$)", user_content, flags=re.IGNORECASE | re.DOTALL)
    if match:
        return " ".join(match.group(1).split())
    return " ".join(user_content.split())


def most_common_heading(examples: list[SynthesisExample], level: str) -> str | None:
    """Return the most common heading text at a markdown heading level."""
    counter: Counter[str] = Counter()
    for example in examples:
        for marker, text in HEADING_PATTERN.findall(example.assistant):
            if marker == level:
                counter[text.strip()] += 1
                break
    return counter.most_common(1)[0][0] if counter else None


def most_common_named_heading(examples: list[SynthesisExample], names: set[str]) -> str | None:
    """Return the most common section heading that matches one of the names."""
    counter: Counter[str] = Counter()
    for example in examples:
        for _marker, text in HEADING_PATTERN.findall(example.assistant):
            normalized = text.strip().lower()
            if normalized in names or any(name in normalized for name in names):
                counter[text.strip()] += 1
    return counter.most_common(1)[0][0] if counter else None


def bullet_line_ratio(text: str) -> float:
    """Return the fraction of non-empty lines formatted as bullets."""
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    if not lines:
        return 0.0
    bullets = sum(1 for line in lines if line.startswith(("- ", "* ")))
    return bullets / len(lines)


def mean_answer_sentences(examples: list[SynthesisExample]) -> float:
    """Return the average number of usable sentences in assistant answers."""
    counts = [len(sentences(example.assistant)) for example in examples]
    return sum(counts) / max(1, len(counts))


def learned_term_weights(examples: list[SynthesisExample], limit: int = 128) -> dict[str, float]:
    """Learn lightweight term salience from reviewed assistant answers."""
    question_terms = Counter(term for example in examples for term in content_terms(example.question))
    answer_terms = Counter(term for example in examples for term in content_terms(example.assistant))
    weights: dict[str, float] = {}
    for term, count in answer_terms.most_common(limit * 3):
        question_count = question_terms.get(term, 0)
        score = math.log1p(count) + 0.35 * math.log1p(question_count)
        if score > 0.7:
            weights[term] = round(score, 4)
        if len(weights) >= limit:
            break
    return weights


def select_evidence_sentences(
    question: str,
    chunks: list[RetrievedChunk],
    term_weights: dict[str, float],
    limit: int,
) -> list[tuple[str, RetrievedChunk]]:
    """Select answer sentences by query overlap, learned salience, and chunk rank."""
    query_terms = set(content_terms(question))
    ranked: list[tuple[float, str, RetrievedChunk]] = []
    for chunk_rank, chunk in enumerate(chunks):
        rank_bonus = 1.0 / (chunk_rank + 1)
        for sentence in sentences(chunk.excerpt):
            terms = content_terms(sentence)
            if not terms:
                continue
            overlap = len(query_terms & set(terms))
            learned = sum(term_weights.get(term, 0.0) for term in terms) / max(1, len(terms))
            score = 2.0 * overlap + learned + 0.25 * float(chunk.score) + rank_bonus
            ranked.append((score, sentence, chunk))
    ranked.sort(key=lambda item: item[0], reverse=True)
    selected: list[tuple[str, RetrievedChunk]] = []
    seen: set[str] = set()
    for score, sentence, chunk in ranked:
        if score <= 0:
            continue
        key = sentence.lower()
        if key in seen:
            continue
        seen.add(key)
        selected.append((sentence, chunk))
        if len(selected) >= limit:
            break
    return selected


def sentences(text: str) -> list[str]:
    """Split text into extractive answer sentence candidates."""
    compact = " ".join(text.split())
    parts = [part.strip() for part in re.split(r"(?<=[.!?])\s+", compact)]
    return [part for part in parts if len(part) > 30] or ([compact] if compact else [])


def content_terms(text: str) -> list[str]:
    """Return lowercased content tokens."""
    return [
        token
        for token in (match.group(0).lower() for match in TOKEN_PATTERN.finditer(text))
        if len(token) > 2 and token not in STOPWORDS
    ]
